---
driver:
  name: vagrant

provisioner:
  name: shell
  script: provision.ps1

platforms:
- name: windows-nano
  driver_config:
    box: mwrock/WindowsNano

verifier:
  name: pester

suites:
  - name: default
